# Generated by Django 3.2.5 on 2021-08-03 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=40)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to='car_pictures')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Econom', 'Econom'), ('Comfort', 'Comfort'), ('Business', 'Business')], default='Econom', max_length=40)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(choices=[('Thermal engine', 'Thermal engine'), ('Electrical engine', 'Electrical engine'), ('Physical engine', 'Physical engine'), ('No info', 'No info')], default='No info', max_length=40)),
                ('pollutant_class', models.CharField(choices=[('class A', 'class A'), ('class B', 'class B'), ('class C', 'class C'), ('class D', 'class D'), ('No info', 'No info')], default='No info', max_length=69)),
                ('price', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Electic', 'Electic'), ('No info', 'No info')], default='No info', max_length=30)),
                ('status', models.CharField(choices=[('On sale', 'On sale'), ('Sold', 'Sold'), ('Ordered', 'Ordered'), ('Archived', 'Archived')], default='Archived', max_length=30)),
                ('doors', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('gear_case', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Robot', 'Robot'), ('Variator', 'Variator'), ('Other type of gearcase', 'Other type of gearcase'), ('No info', 'No info')], default='No info', max_length=40)),
                ('numbers', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=255)),
                ('sitting_place', models.PositiveIntegerField()),
                ('first_registration_date', models.DateField(auto_now_add=True)),
                ('engine_power', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.color')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealers')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model')),
                ('property', models.ManyToManyField(to='cars.Property')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
