# Generated by Django 3.2.5 on 2021-08-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'меню'},
        ),
        migrations.RemoveField(
            model_name='restik',
            name='dish',
        ),
        migrations.AlterField(
            model_name='restik',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_net.city'),
        ),
        migrations.AlterField(
            model_name='restik',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_net.country'),
        ),
        migrations.AlterField(
            model_name='restik',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_net.menu'),
        ),
    ]
