# Generated by Django 3.2.5 on 2021-08-01 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_net', '0002_auto_20210801_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_net.menu'),
            preserve_default=False,
        ),
    ]
